meta_product_name: "L'addition SVP"
meta_title: "L'addition SVP - Réservez, Commandez, Dégustez"
meta_description: "Relevant description"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
